#SPDX-License-Identifier: MIT-0
---
app_root: /opt/yolo
app_repo_url: https://github.com/bree254/yolo.git
app_repo_branch: master
app_user: vagrant

docker_network_name: yolo-net
mongo_volume_name: mongo-data

frontend_container_name: yolo-frontend
backend_container_name: yolo-backend
database_container_name: yolo-mongo

frontend_host_port: 3000
backend_port: 5000
database_port: 27017
