---
- name: Provision containerized YOLO e-commerce app
  hosts: default
  become: true
  roles:
    - { role: project_setup, tags: ['project_setup'] }
    - { role: docker, tags: ['docker'] }
    - { role: app_code, tags: ['app_code'] }
    - { role: frontend, tags: ['frontend'] }
    - { role: backend, tags: ['backend'] }
    - { role: database, tags: ['database'] }
