#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/backend
backend_image: bree254/yolo-backend:v1.0.0
backend_container_name: yolo-backend
backend_port: 5000
backend_env:
  PORT: "5000"
  MONGODB_URI: "mongodb://{{ database_container_name | default('yolo-mongo') }}:{{ database_port | default(27017) }}/yolomy"
