#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/backend
backend_image: bree254/yolo-backend:v1.0.0
backend_port: 5000
backend_env:
  PORT: "5000"
  MONGODB_URI: mongodb://yolo-mongo:27017/yolomy
