#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/backend
- name: Build backend image
  community.docker.docker_image:
    name: "{{ backend_image }}"
    build:
      path: "{{ app_root }}/backend"
      target: prod
    source: build

- name: Run backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    restart_policy: unless-stopped
    command: ["node", "server.js"]
    published_ports:
      - "{{ backend_port }}:5000"
    env: "{{ backend_env }}"
    networks:
      - name: "{{ docker_network_name }}"
